apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Values.db.labels.app }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: {{ .Values.db.name }}
  selector:
    app: {{ .Values.db.labels.app }}
  clusterIP: None