apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ .Values.web.labels.app }}
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: {{ .Values.web.name }}
  selector:
    app: {{ .Values.web.labels.app }}
  type: LoadBalancer